### ISSUE TITLE
compatible with node 14 ?

### ISSUE THREAD

**Issue by jorgheymans** [erosb/mvn-search#14]
Hi,

Is it possible that updating node to release 14 broke mvn-search ? I know nothing about node, but it's the only thing i can think of that might explain why "suddenly" it stopped working:

```
$ node --version
v14.18.0
$ mvn-search liquibase-core
(node:44921) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at mvnSearchResponseArrived (/home/user/.npm-global/lib/node_modules/@erosb/mvn-search/src/index.js:73:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by jorgheymans** [comment]
For some reason, reinstalling and updating npm solved the issue:

```
npm install -g @erosb/mvn-search
npm install -g npm
```

**Comment by jorgheymans** [comment]
could have caused the issue as well yes, in any case it's working again
now. Thanks again for this great tool !
