### ISSUE TITLE
SyntaxError: Unexpected end of JSON input for the last two or three days

### ISSUE THREAD

**Issue by oscerd** [erosb/mvn-search#15]
It's two or three days I'm getting this error while using mvn-search

```
(node:24336) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at mvnSearchResponseArrived (/usr/lib/node_modules/@erosb/mvn-search/src/index.js:73:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by oscerd** [comment]
Seems to be ok.
